### ISSUE TITLE
unsupport StS

### ISSUE THREAD

**Issue by Purewolfgang** [kiooeht/ModTheSpire#106]
Hello I recently found out that you could mod slay the spire and tried to do it, at first I was getting the ModTheSpire to successfully launch but a few of the mods wouldn't work and every time I tried to launch the game it would just give me a black screen, when I went back to find out the issue the mod launched was saying that my StS version was StS 10-11-2018 but the mod explicitly supports StS 10-04-2018, does that mean I have to downgrade the MtS  launcher to get it to be 10-04-2018? because I am completely lost here, I also don't want to lose the ability to run my other mods that I already have working.

**Comment by Purewolfgang** [comment]
Windows cannot find '.\jre\bin\javaw.exe'. Make sure you typed the name correctly, and the try again. Is what shows up when I try to launch from the MTS Command, so I switched the  Modthe Spire and desktop- 1.0.jar files accordingly and tried to launch from steam with no luck either

**Comment by yhrcyt** [comment]
Hey Purewolfgang,
The first question: Yes. you need to downgrade it in order to play that mod. Also you need to downgrade all the other mods. 10-11-2018 patch is not backward-compatible for character mods.

The second question: That's so weird. When you download the game, the game download java for you in the game folder. Did you change your system environment variables `PATH` or `JAVA_HOME` before? I don't know how Mod the Spire work so I'm just guessing.

**Comment by kiooeht** [comment]
You don't **have** to downgrade to use that mod. The notice about a mod explicitly supporting version just means that the last release was tested by the author to work on that version of StS, it *may* still work on newer versions.
That said, the 10-11-2018 version of StS had some major rewrites that broke BaseMod. In turn, updating BaseMod to work broke a lot of other mods (mostly character mods). As a rule of thumb, if a character mod hasn't been updated for 10-11-2018, it won't work.

**Comment by yhrcyt** [comment]
"a few of the mods won't work" already shows that they're not compatible. so in order to get in to work, downgrade is needed. also BaseMod 4.x.x (and lots of other mods) is not compatible with 10-4-2018, so they most likely need a downgrade.

however few mods are compatible with both version and that's ok.

what mods are you playing? I can help update them.

**Comment by Purewolfgang** [comment]
I have not changed the system environment's ever because I don't even know how to do that, and in response to what mods I am playing I am basically playing all the different character mods along with a splash of others like always whale a few of the shops ones and any other mod that adds a lot of cards or needs to be in for character mods to work. I have gotten the Mod launcher to load and launch a game since this post but instead of being able to play all it does is show a black screen and locks up one of my monitor's until I force close the launcher.
