### ISSUE TITLE
Duplicated mods and eternal updates

### ISSUE THREAD

**Issue by qvanleersum** [kiooeht/ModTheSpire#119]
I have, over time, deleted and redownloaded mods multiple times (specifically Blakk mod and Marisa), and now, these mods are in my mod list multiple times, and every time I check for updates, it states that these mods have an update, despite there not being one. On top of that, it also shows the mods multiple times, likely depending on the amounts of deletion and redownloads I have done. I would assume this to not be expected behavior. However, I may have screwed up the program as well.

The following images show the issues:
Marisa mod is listed multiple times:
![afbeelding](https://user-images.githubusercontent.com/23501898/49078464-628b7180-f23e-11e8-8d9a-0485ae3fee8a.png)

Blakk mod, also listed twice, 'has an update', after already updating once
![afbeelding](https://user-images.githubusercontent.com/23501898/49078447-53a4bf00-f23e-11e8-8b53-f4312ac8d1d0.png)

The following updates are available, after already updating once
![afbeelding](https://user-images.githubusercontent.com/23501898/49078426-44be0c80-f23e-11e8-8045-03f6ca3ff3b9.png)

**Comment by kiooeht** [comment]
This isn't anything you've done, this is because of the authors of those mods doing non-standard things.

Marisa appends their version number to the filename of every release jar, so end up with `TS05_Marisa_v0.14.4.jar` and `TS05_Marisa_v0.14.3.jar` both appearing in MTS after updating. You can fix it by manually deleting the older version from your mods folder.

Blakk Mod moved repository (renaming from BlakkMod to BlakkModd) for reasons I don't know. 2.0 is the last version released on the old repository and points to the new repository for updates. Again, delete the older version and you should be good.

**Comment by qvanleersum** [comment]
The issues with Marisa have indeed been resolved. However, I still have a Blakk Mod version 1.4 in my list, despite not having blakk mod installed at all (removed it to try and get rid of the issues altogether).

![afbeelding](https://user-images.githubusercontent.com/23501898/49149728-240fb880-f30b-11e8-97c5-7017abdec4f3.png)

![afbeelding](https://user-images.githubusercontent.com/23501898/49149737-2b36c680-f30b-11e8-9310-d409915839c2.png)

**Comment by kiooeht** [comment]
Looks like v1.4 of BlakkMod named its file "ExampleMod.jar" <https://github.com/blakkthunderr/Blakkmod/releases/tag/1.4>.
