### ISSUE TITLE
Supporting newer Java versions

### ISSUE THREAD

**Issue by squedgy** [kiooeht/ModTheSpire#197]
So this is more to allow and open up a discussion on the topic as a way to gauge interest in supporting this, as well as allow for the possibility. There's more than a few reasons, but the biggest one for me is that supporting the newer Java features for mod developers is preferable from their standpoint (at least from mine). I actually have a fork that supports JDK 9+ (tested with OpenJDK 8U292, 11, 14, and 17 on Ubuntu 22.04).

So, the issue is really about if there's interest in supporting Java versions after 8, or should this be kept side-lined.

Hopefully this is the appropriate place to open this up. I'll include the a link to the fork below for completeness sake.

https://github.com/squedgy/ModTheSpire/tree/squedgy-newer-java

**Comment by kiooeht** [comment]
Unfortunately it's kind of pointless to add support for Java 9+. Slay the Spire ships with a copy of Java 8 and that's what gets used when you launch the game or MTS via Steam. Because of this, 99% of players will only ever run the game with Java 8 and any mods made with Java 9+ will not function for them.
