### ISSUE TITLE
need a new version of mod the spire.

### ISSUE THREAD

**Issue by Downanddirty4568** [kiooeht/ModTheSpire#39]
ever since the latest update on slay the spire, mod the spire has not been working for me, even though i have all of the same files i had before when it was working perfectly fine, other than updating my base mods, i havent done anything that could have possibly messed it up for me, so i am thinking that we just need a new version of ModTheSpire since the current one im using is the latest one and it is extremely outdated, the last time there was an update to modthespire was march 31st its now may 3rd.

**Comment by kiooeht** [comment]
[Again](https://github.com/kiooeht/ModTheSpire/issues/37), this is not a problem with ModTheSpire. ModTheSpire still works with the latest update, this is a problem with the game updating and mods not updating to stay compatible.

The week 22 patch of Slay the Spire changed a lot of things in the code that broke compatibility with a lot of mods, mainly any mods that add new characters.

When you say you updated your base mods, I assume you're talking about grabbing the [latest release of BaseMod](https://github.com/daviscook477/BaseMod/releases), which added compatibility with the week 22 patch. While that release of BaseMod added support for the week 22 patch, any character mods that haven't updated since are still broken. The only mod I know of that has updated since the week 22 patch is the Black Mage mod, so any other character mods you're trying to use will not work.
