### ISSUE TITLE
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.

### ISSUE THREAD

**Issue by Shadowh8ter** [kiooeht/ModTheSpire#50]
Managed to run everything on my PC just fine, however I can't seem to make it run on my mothers PC.

Her video drivers are up to date so I don't think it's that. I saw the top response from this link https://stackoverflow.com/questions/15572908/opengl-is-not-supported-by-the-video-driver

And was going to attempt that but have no idea what file in the source code I should edit to do so. Any help/suggestions?

**Comment by kiooeht** [comment]
This is a weird one.
Is it just playing modded that causes the problem? Does running Slay the Spire normally still work?
What about running it through ModTheSpire but without any mods?

**Comment by Shadowh8ter** [comment]
Yeah I should have mentioned that. I tried running mod the spire without any mods on and still got the same error code. Running Slay the Spire normally works on the PC just fine, she has 200 of my 245 hours on that PC.

The graphics card is a basic integrated intel graphics card so I assume that's why this problem is arising. I can post a pastebin of the full text I get, maybe that'd help you know where it breaks down?  

https://pastebin.com/TZ9DqAdf

**Comment by JeSuisUnCaillou** [comment]
I have the exact same problem, and I was about to paste the exact same logs. +1

**Comment by JeSuisUnCaillou** [comment]
> Yeah I should have mentioned that. I tried running mod the spire without any mods on and still got the same error code. Running Slay the Spire normally works on the PC just fine, she has 200 of my 245 hours on that PC.
> 
> The graphics card is a basic integrated intel graphics card so I assume that's why this problem is arising. I can post a pastebin of the full text I get, maybe that'd help you know where it breaks down?
> 
> https://pastebin.com/TZ9DqAdf

I have the exact same problem, and I was about to paste the exact same logs. +1

**Comment by kiooeht** [comment]
Finally figured out a solution for this.
The problem comes from an interaction with old Intel integrated graphics drivers, Windows 10, and newer versions of Java.
The solutions involve either not using Windows 10, patching your graphics drivers, or using an older version of Java. The latter being a lot easier that the other two.

First, download this version of Java:
https://files.multimc.org/downloads/jre-8u51-windows-x64.zip
Extract it into your Slay the Spire folder. It should look like this: 
![explorer_2018-11-15_15-48-23](https://user-images.githubusercontent.com/236842/48588937-fe87b580-e8ed-11e8-8571-da71b615b124.png)

Then, download [MTS_8u51.cmd](https://raw.githubusercontent.com/kiooeht/ModTheSpire/master/MTS_8u51.cmd) and put it into your Slay the Spire folder.
If you got both right, running `MTS_8u51.cmd` will open ModTheSpire and you'll be able to use mods without this crash.

**Comment by duduelo** [comment]
but the last download thing just opens a website

**Comment by luismuchaki** [comment]
@duduelo the link contains a .cmd file, you can right click > save as....
You may need to update the location of ModTheSpire.jar inside the cmd file. Example of my updated cmd file: 
start .\jre1.8.0_51\bin\javaw.exe -jar D:\SteamLibrary\SteamApps\workshop\content\646570\1605060445\ModTheSpire.jar

**Comment by Xaralabos23** [comment]
i was having a little trouble with the .cmd and in the end i ended up with a "Unable to find 'desktop-1.0.jar' " error
then i realized the cmd isnt even needed, just do step 1 (download the java version and place it on the folder) and start moded StS from steam
if the vanila version crashes on start, open the SlayTheSpire.exe from the folder

**Comment by Vihanga101** [comment]
thank you, it worked <3

**Comment by vgvubl** [comment]
Just made my GitHub account to thank you, it worked flawlessly.
