### ISSUE TITLE
Can't start get past the mods list.

### ISSUE THREAD

**Issue by Dorante997** [kiooeht/ModTheSpire#83]
So, i'm new to this kind of stuff, be patient please:

I bought STS a few days ago. Super fun, super challenging, sometimes unfair and so on.
Today i tried to mod it, i downloaded mod the spire and put it into my directory, downloaded the mods, put them into the "mods" folder in the directory and started mod the spire from its own jar file.

I get the list of mods, select all of them, press play and...

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (08-23-2018)
 - ModTheSpire (3.0.0)
Mod list:
 - basemod (3.0.2)
 - betterrewardsmod (4.0.2)
 - BlackRuseMod (0.9.2)
 - Custom Cards
 - Friendly_Minions_0987678 (0.1)
 - HexCores
 - MadScienceMod (0.2.1)
 - ReplayTheSpireMod (1.0.12)
 - STS_AlwaysWhale (0.0.1)
 - Synergy Relic
 - The Valiant
 - witchmod (1.0.0)
 - Team TouhouSpire 04 - Yuyuko (0.2.1)
 - NecroMod

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: valiant.Patches.VampirePatch
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:217)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:176)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javassist.NotFoundException: com.megacrit.cardcrawl.events.thecity.Vampires
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:211)
	... 4 more

I get this. Tried installing java 8 but nothing changes. Tried removing the valiant mod (com.evacipated.cardcrawl.modthespire.patcher.**PatchingException: valiant.**Patches.VampirePatch) but it just change to another mod. Tried using the debug option, but the warning is always the same. Tried different versions, nothing changes.

Any idea? I would really love to play with mods T.T

**Comment by KongMD-Steam** [comment]
@Dorante997 
A number of mods were broken by a recent large change in BaseMod (the mod that most class mods depend on). Many mod authors have updated their mods so that they are working, but there are few that are still not functional. From the error you posted, the game won't launch because The Valiant is enabled.

My recommendation is to start with a few mods at first, then gradually enable more mods as you go along. Also, **always** have BaseMod first in your mod order.

On the Slay the Spire Discord server, the community maintains a list of mods that are known to not work with current weekly patch (39):
* Necromancer
* Valiant
* Juggernaut
* Seeker
* Spike's Relics
* Custom Cards

**Comment by Dorante997** [comment]
I managed to start the game with the mods after removing the followings:

Custom cards
Necro mod
Synergic relic
The valiant
Yuyuko mod

That's sad because i really wanted to try the valiant and the synergic ones, but no worries, i just tried one of the other extra classes installed and it was super fun xD
